const intents = [
  { id:"resumo_ari", keywords:["resume","resuma","fale mais","tell me more","conta o que","preciso saber","need to know","quem e ele","who is he","me conta","resumo","summary","overview","geral","general","tudo sobre","all about","conta sobre ele","sobre ele"],
    pt:"O Ari \u00e9 o Ari Francisco Fagundes, 28 anos, Tecn\u00f3logo em Sistemas para Internet pela UniAvan. 8 anos de Suporte T\u00e9cnico em empresas como CIGAM, Unifique, Clinitec e DATAPINE. Domina redes, banco de dados, APIs, hardware e UX/UI.",
    en:"Ari is Ari Francisco Fagundes, 28yo, graduated in Systems for the Internet from UniAvan. 8 years of Tech Support at CIGAM, Unifique, Clinitec and DATAPINE.",
    page:"resumo", pageLabelPt:"Ver Curr\u00edculo", pageLabelEn:"See Resume" },
  { id:"quem", keywords:["quem","quem e","who","who is","fale sobre","tell me about","me fala","descreve","describe","apresent","esse cara","this guy"],
    pt:"Ari Francisco Fagundes, 28 anos, nascido em 31/10/1997. 8 anos em Suporte T\u00e9cnico, formado em Sistemas para Internet. Vive entre redes, hardware e c\u00f3digo!",
    en:"Ari Francisco Fagundes, 28yo, born 10/31/1997. 8 years in Tech Support, graduated in Systems for the Internet!" },
  { id:"nome", keywords:["nome completo","full name","nome dele","his name","nome todo","sobrenome","last name","primeiro nome","first name","como ele se chama","what is his name","francisco","fagundes"],
    pt:"Ari Francisco Fagundes!",
    en:"Ari Francisco Fagundes!" },
  { id:"idade", keywords:["idade","quantos anos","age","how old","old is","nasceu","born","aniversario","birthday","data de nascimento","date of birth"],
    pt:"Nasceu em 31/10/1997, tem 28 anos. Sim, \u00e9 do Halloween!",
    en:"Born 10/31/1997, he's 28. Yes, a Halloween baby!" },
  { id:"hobby", keywords:["hobby","hobbies","gosta","like","likes","diverte","fun","tempo livre","free time","lazer","leisure","jogo","game","musica","music","esporte","sport","interesse","interest","faz nas horas","o que faz quando","pessoal","personal"],
    pt:"Ele adora conhecer cidades do interior de moto, curte sair \u00e0 noite pra lugares calmos e tem um gosto por coisas simples. Em casa, fica no PC assistindo, jogando e acompanhando f\u00f3runs de tecnologia pra ficar por dentro das novidades!",
    en:"He loves exploring small towns by motorcycle, enjoys going out to calm places at night and appreciates simple things. At home, he's on his PC watching, gaming and following tech forums to stay up to date!" },
  { id:"curiosidades", keywords:["curiosidade","curiosidades","curioso","curious","fun fact","fato curioso","interessante","interesting","sabia que","did you know","diferente","different","surpreend","surpris"],
    pt:"Curiosidades? Ele j\u00e1 fez aula de piloto a\u00e9reo com 18 anos, come\u00e7ou faculdade de Engenharia Mec\u00e2nica antes de migrar pra TI, e tentou empreender com a Greatic.io. Vida intensa!",
    en:"Fun facts? He took pilot lessons at 18, started Mechanical Engineering before switching to IT, and tried entrepreneurship with Greatic.io. Intense life!" },
  { id:"projeto_marcou", keywords:["projeto marcou","project marked","marcou a vida","marcou a carreira","career highlight","maior conquista","biggest achievement","orgulho","proud","destaque","highlight","case","principal projeto","main project"],
    pt:"Dois projetos marcaram: na Unifique, liderou a implanta\u00e7\u00e3o de fibra dedicada Brusque-SP para a Havan, trabalhando com a equipe de infra deles em defini\u00e7\u00e3o t\u00e9cnica e desenho de rede. E a Greatic.io, onde empreendeu com projetos web e aprendeu sobre atendimento ao cliente e gest\u00e3o de neg\u00f3cio!",
    en:"Two projects stood out: at Unifique, he led the dedicated fiber implementation Brusque-SP for Havan, working with their infra team. And Greatic.io, where he entrepreneured with web projects and learned client service and business management!" },
  { id:"case_havan", keywords:["havan","fibra dedicada","dedicated fiber","brusque","projeto estrategico"],
    pt:"Atuou em projeto estrat\u00e9gico na Unifique: fibra dedicada entre Brusque (SC) e S\u00e3o Paulo (SP) para a Havan. Trabalhou com a equipe de infraestrutura da Havan na defini\u00e7\u00e3o t\u00e9cnica, requisitos e desenho de rede. Refor\u00e7ou networking, troubleshooting e comunica\u00e7\u00e3o com cliente!",
    en:"Strategic project at Unifique: dedicated fiber between Brusque (SC) and S\u00e3o Paulo (SP) for Havan. Worked with Havan's infra team on technical definition, requirements and network design!",
    page:"resumo", pageLabelPt:"Ver Experi\u00eancias", pageLabelEn:"See Experience" },
  { id:"piloto", keywords:["piloto","pilot","aviao","airplane","aereo","aerial","voar","fly"],
    pt:"Sim! Com 18 anos ele fez aula de piloto a\u00e9reo. N\u00e3o seguiu carreira, mas a experi\u00eancia ficou!",
    en:"Yes! At 18 he took aerial pilot lessons. Didn't pursue it, but the experience stuck!" },
  { id:"engenharia", keywords:["engenharia","engineering","mecanica","mechanical","outra faculdade","another degree"],
    pt:"Ele come\u00e7ou Engenharia Mec\u00e2nica, mas descobriu que sua paix\u00e3o era tecnologia e migrou pra Sistemas para Internet. Melhor decis\u00e3o!",
    en:"He started Mechanical Engineering but found his passion was technology and switched to Systems for the Internet. Best decision!" },
  { id:"nivel_exp", keywords:["nivel de experiencia","experience level","junior","pleno","senior","senioridade","seniority","qual nivel","what level","jr","mid","sr"],
    pt:"8 anos = Pleno/S\u00eanior. Na CIGAM foi Analista N2 S\u00eanior, na Unifique e Clinitec atuou como Pleno. Bagagem pesada!",
    en:"8 years = Mid/Senior. Senior N2 at CIGAM, Mid-level at Unifique and Clinitec!" },
  { id:"atendimento", keywords:["atendimento","atendimento ao cliente","customer service","cliente","client","b2c","b2b","relacionamento"],
    pt:"8 anos atendendo B2C e B2B por telefone, email e webchat. Sabe ouvir, diagnosticar r\u00e1pido e comunicar a solu\u00e7\u00e3o de forma clara!",
    en:"8 years serving B2C & B2B via phone, email & webchat. Listens, diagnoses fast, communicates clearly!" },
  { id:"troubleshooting", keywords:["troubleshooting","diagnostico","diagnosis","resolver problema","solve problem","debug","depurar","investigar","investigate","root cause","causa raiz"],
    pt:"Troubleshooting \u00e9 o forte! Wireshark, an\u00e1lise de logs, debug de APIs no Postman, investiga\u00e7\u00e3o de causa raiz. No projeto da Havan resolveu pontos cr\u00edticos em tempo real!",
    en:"Troubleshooting is his strength! Wireshark, log analysis, API debugging in Postman, root cause investigation!" },
  { id:"incidentes", keywords:["incidente","incident","chamado","ticket","ocorrencia","escalonamento","escalation","sla","itil"],
    pt:"Gest\u00e3o de incidentes em todas as empresas! Abertura, acompanhamento, escalonamento, documenta\u00e7\u00e3o e cumprimento de SLA!",
    en:"Incident management at every company! Opening, tracking, escalating, documenting and meeting SLAs!" },
  { id:"suporte_niveis", keywords:["suporte","support","n1","n2","helpdesk","help desk","tecnico","technical"],
    pt:"Suporte T\u00e9cnico \u00e9 o DNA! N1 e N2 S\u00eanior na CIGAM, Pleno na Unifique/Clinitec. Diagn\u00f3stico r\u00e1pido e documenta\u00e7\u00e3o impec\u00e1vel!",
    en:"Tech Support is his DNA! Senior N2 at CIGAM, Mid-level at Unifique/Clinitec!" },
  { id:"infra_sistemas", keywords:["infraestrutura","infrastructure","ti","it"],
    pt:"Infra de TI na DATAPINE (rede interna, Windows AD, servidores) e sistemas ERP na CIGAM. Vis\u00e3o completa!",
    en:"IT infra at DATAPINE (network, Windows AD, servers) and ERP systems at CIGAM!" },
  { id:"erp_cigam", keywords:["erp","gestao","management","pdv","pos","cigam"],
    pt:"Na CIGAM trabalhou com o ERP CIGAM: suporte B2B, atualiza\u00e7\u00f5es de PDV, queries PostgreSQL/MySQL, integra\u00e7\u00e3o de APIs e tirando d\u00favidas de usu\u00e1rios!",
    en:"At CIGAM he worked with CIGAM ERP: B2B support, POS updates, PostgreSQL/MySQL queries, API integration!",
    page:"resumo", pageLabelPt:"Ver Experi\u00eancias", pageLabelEn:"See Experience" },
  { id:"diferencial", keywords:["diferencial","differenti","destaca","stand out","por que contratar","why hire","ponto forte","strength","qualidade","quality","melhor","best"],
    pt:"O diferencial dele? Vis\u00e3o completa de TI (hardware ao c\u00f3digo), comunica\u00e7\u00e3o clara com cliente, proatividade e 8 anos de bagagem real. N\u00e3o \u00e9 teoria, \u00e9 pr\u00e1tica!",
    en:"His edge? Full IT vision (hardware to code), clear client communication, proactivity and 8 years of real experience!" },
  { id:"trabalho_equipe", keywords:["equipe","team","trabalho em equipe","teamwork","lideranca","leadership","colabora","collaborat","grupo","group"],
    pt:"Trabalha bem em equipe! No projeto da Havan coordenou com a equipe de infra do cliente. Na CIGAM, fazia escalonamento e colaborava com devs e analistas!",
    en:"Great teamwork! On the Havan project he coordinated with the client's infra team. At CIGAM he escalated and collaborated with devs!" },
  { id:"disponibilidade", keywords:["disponibilidade","availability","quando pode","when can","comecar","start","inicio","begin","imediato","immediate","pronto","ready"],
    pt:"Ele est\u00e1 dispon\u00edvel para novas oportunidades! Melhor combinar direto com ele no WhatsApp.",
    en:"He's available for new opportunities! Best to arrange directly via WhatsApp.",
    page:"contato", pageLabelPt:"Ver Contato", pageLabelEn:"See Contact" },
  { id:"pretensao", keywords:["pretensao","salary","salario","remuneracao","compensation","quanto ganha","how much","quanto quer","paga","pay","valor"],
    pt:"Essa \u00e9 confidencial! Melhor alinhar direto com ele no WhatsApp.",
    en:"That's confidential! Best to discuss directly via WhatsApp.",
    page:"contato", pageLabelPt:"Falar com Ari", pageLabelEn:"Talk to Ari" },
  { id:"experiencia", keywords:["experiencia","experience","quanto tempo","how long","quantos anos de","years of","trabalha ha","carreira","career","trajetoria","trajectory"],
    pt:"8 anos! DATAPINE (Infra TI), Clinitec e Unifique (Telecom) e CIGAM (ERP). B2C, B2B, telefone, e-mail, webchat... j\u00e1 fez de tudo.",
    en:"8 years! DATAPINE, Clinitec & Unifique (Telecom) and CIGAM (ERP). B2C, B2B, phone, email, webchat!",
    page:"resumo", pageLabelPt:"Ver Experi\u00eancias", pageLabelEn:"See Experience" },
  { id:"experiencia_longa", keywords:["mais longa","longest","maior experiencia","mais tempo","ficou mais","stayed the longest"],
    pt:"CIGAM Software (Abr/2023 a Nov/2025), Analista N2 S\u00eanior. Virou fera em ERP, banco de dados e APIs!",
    en:"CIGAM Software (Apr/2023-Nov/2025), Senior N2 Analyst!",
    page:"resumo", pageLabelPt:"Ver Experi\u00eancias", pageLabelEn:"See Experience" },
  { id:"unifique", keywords:["unifique","telecom","isp","provedor"],
    pt:"Unifique (2022-2023), Analista Pleno. MikroTik, CISCO, Juniper, BGP, OSPF, MPLS, Zabbix/PRTG. E o projeto de fibra dedicada pra Havan!",
    en:"Unifique (2022-2023), Mid-level. MikroTik, CISCO, Juniper, BGP, OSPF, MPLS plus the Havan fiber project!",
    page:"resumo", pageLabelPt:"Ver Experi\u00eancias", pageLabelEn:"See Experience" },
  { id:"clinitec", keywords:["clinitec"],
    pt:"Clinitec (2020-2022): monitoramento com The Dude e Zabbix, APs MikroTik, FTTB, links dedicados e PtP!",
    en:"Clinitec (2020-2022): monitoring with The Dude & Zabbix, MikroTik APs, FTTB!",
    page:"resumo", pageLabelPt:"Ver Experi\u00eancias", pageLabelEn:"See Experience" },
  { id:"datapine", keywords:["datapine"],
    pt:"DATAPINE (2019-2020): rede interna, hardware, Windows AD, APIs e testes funcionais!",
    en:"DATAPINE (2019-2020): internal networks, hardware, Windows AD, APIs!",
    page:"resumo", pageLabelPt:"Ver Experi\u00eancias", pageLabelEn:"See Experience" },
  { id:"api", keywords:["api","postman","endpoint","rest","restful","requisicao","request","json","webhook"],
    pt:"API \u00e9 com ele! REST, Postman, JSONs, integra\u00e7\u00e3o e webhooks. Na CIGAM e DATAPINE era rotina!",
    en:"APIs are his thing! REST, Postman, JSONs, integration & webhooks!" },
  { id:"banco", keywords:["banco de dados","database","mysql","postgre","postgresql","sql","query","consulta","tabela","table","dados","data"],
    pt:"MySQL e PostgreSQL! Queries, atualiza\u00e7\u00f5es em massa, diagn\u00f3stico de inconsist\u00eancias. Na CIGAM era di\u00e1rio!",
    en:"MySQL & PostgreSQL! Queries, bulk updates, inconsistency diagnostics!" },
  { id:"hardware", keywords:["hardware","computador","computer","pc","placa","motherboard","memoria","ram","hd","ssd","processador","cpu","manutencao","maintenance","equipamento","equipment","pdv","terminal"],
    pt:"Hardware \u00e9 onde come\u00e7ou! Manuten\u00e7\u00e3o preventiva/corretiva, diagn\u00f3stico de placas, terminais PDV!",
    en:"Hardware is where he started! Preventive & corrective maintenance, POS terminals!" },
  { id:"monitoramento", keywords:["monitoramento","monitoring","zabbix","grafana","prtg","the dude","netnumen","unm","alerta","alert","dashboard"],
    pt:"Zabbix, Grafana, PRTG, The Dude, ZTE NetNumen e UNM! Dashboards e alertas em tempo real!",
    en:"Zabbix, Grafana, PRTG, The Dude, ZTE NetNumen & UNM!" },
  { id:"wireshark", keywords:["wireshark","pacote","packet","captura","capture","sniffer","trafego","traffic"],
    pt:"Wireshark: captura e an\u00e1lise de pacotes, debug de tr\u00e1fego e investiga\u00e7\u00e3o de conectividade!",
    en:"Wireshark: packet capture, traffic debugging & connectivity troubleshooting!" },
  { id:"redes", keywords:["rede","network","tcp","ip","dns","dhcp","firewall","switch","router","roteador","vlan","vpn","wifi","wireless","ospf","bgp","mpls","radius","wan","lan"],
    pt:"Redes \u00e9 a especialidade! TCP/IP, DNS, DHCP, VPN, VLAN, OSPF, BGP, MPLS, RADIUS, Firewall. MikroTik, CISCO e Juniper!",
    en:"Networking is his specialty! TCP/IP, DNS, DHCP, VPN, VLAN, OSPF, BGP, MPLS, MikroTik, CISCO & Juniper!" },
  { id:"uxui", keywords:["ux","ui","design","interface","figma","prototipo","prototype","usabilidade","wireframe","layout"],
    pt:"UX/UI? Estudou na faculdade e aplica em projetos web! Esse portf\u00f3lio \u00e9 prova!",
    en:"UX/UI? Studied in college & applies in web projects! This portfolio is proof!" },
  { id:"formacao", keywords:["formado","formou","graduado","graduacao","faculdade","universidade","university","college","estudou","estudo","education","graduated","degree","diploma","curso superior","ensino superior","bacharel","tecnologo","sistemas","internet","formacao","onde estudou","uniavan","avantis"],
    pt:"Tecn\u00f3logo em Sistemas para Internet pela UniAvan, formado final de 2023!",
    en:"Systems for the Internet from UniAvan, graduated end of 2023!",
    page:"resumo", pageLabelPt:"Ver Forma\u00e7\u00e3o", pageLabelEn:"See Education" },
  { id:"certificados", keywords:["certificado","certificacao","certificados","certification","certified","mikrotik","mtcna","senai","curso","cursos","courses","treinamento","training","qualificacao"],
    pt:"MikroTik pela Udemy (90h, 2021). T\u00e9cnico de Redes pelo SENAI (960h, 2014-2016)!",
    en:"MikroTik via Udemy (90h, 2021). Network Technician from SENAI (960h, 2014-2016)!",
    page:"resumo", pageLabelPt:"Ver Cursos", pageLabelEn:"See Courses" },
  { id:"cnh", keywords:["cnh","habilitacao","carteira de motorista","driver","license","dirigir","drive","carro","car","categoria"],
    pt:"CNH B!",
    en:"Category B driver's license!" },
  { id:"empresa", keywords:["greatic","empresa dele","his company","negocio","business","empreendedor","entrepreneur","dono","owner","fundou","founded","agencia","agency"],
    pt:"Ele possui experi\u00eancia com projetos web na Greatic.io, onde desenvolveu habilidades de atendimento ao cliente e resolu\u00e7\u00e3o de problemas. Atualmente est\u00e1 focado em oportunidades na \u00e1rea de suporte t\u00e9cnico.",
    en:"He has web project experience at Greatic.io, developing client service and problem-solving skills. Currently focused on technical support opportunities." },
  { id:"habilidades", keywords:["habilidade","habilidades","skill","skills","sabe fazer","can do","competencia","o que ele faz","what does he do","faz o que","trabalha com","works with","domina","master","tecnologia","tech"],
    pt:"Redes (TCP/IP, BGP, OSPF, MPLS), Hardware, Banco de Dados (MySQL, PostgreSQL), APIs (REST, Postman), Monitoramento (Zabbix, Grafana, Wireshark), UX/UI e Programa\u00e7\u00e3o!",
    en:"Networks, Hardware, Databases, APIs, Monitoring (Zabbix, Grafana, Wireshark), UX/UI & Programming!" },
  { id:"ferramentas", keywords:["ferramenta","ferramentas","tool","tools","usa","uses","programa","programs","software"],
    pt:"Zabbix, Grafana, Wireshark, PRTG, The Dude, ZTE NetNumen, UNM, Postman, MikroTik, CISCO e Juniper!",
    en:"Zabbix, Grafana, Wireshark, PRTG, The Dude, Postman, MikroTik, CISCO, Juniper!" },
  { id:"conhecimento", keywords:["nivel","conhecimento","knowledge","level","competente","capaz","capable","inteligente","smart","talento","manja","entende","sabe"],
    pt:"Avan\u00e7ado em redes e infraestrutura, intermedi\u00e1rio-avan\u00e7ado em banco de dados e APIs, crescendo em front-end!",
    en:"Advanced in networking & infra, mid-to-advanced in databases & APIs, growing in front-end!" },
  { id:"bom", keywords:["bom","good","great","otimo","excelente","excellent","vale a pena","worth","recomend","recommend","presta","confia","trust","confiar"],
    pt:"Se ele \u00e9 bom? Na minha opini\u00e3o ele \u00e9 \u00f3timo no que faz! Pode confiar.",
    en:"Is he good? In my opinion, he's great at what he does!" },
  { id:"contratar", keywords:["contratar","contrat","hire","hiring","emprego","job","vaga","vacancy","disponivel","available","recrutamento","recruiting","freelancer","freelance","proposta","proposal","orcamento","budget","preco","price","cobr","charge","custa","cost"],
    pt:"Quer contratar? Dedicado, resolve problemas como ningu\u00e9m. Chama no WhatsApp!",
    en:"Want to hire? Dedicated, solves problems like no one else!",
    page:"contato", pageLabelPt:"Ver Contato", pageLabelEn:"See Contact" },
  { id:"contato", keywords:["contato","contact","falar com","talk to","chamar","ligar","call","email","telefone","phone","whatsapp","wpp","zap","numero","number","linkedin","github"],
    pt:"WhatsApp \u00e9 o mais r\u00e1pido! Tamb\u00e9m est\u00e1 no LinkedIn e GitHub.",
    en:"WhatsApp is fastest! Also on LinkedIn and GitHub.",
    page:"contato", pageLabelPt:"Ver Contato", pageLabelEn:"See Contact" },
  { id:"localizacao", keywords:["mora","morar","live","lives","cidade","city","estado","state","pais","country","brasil","brazil","santa catarina","sc","regiao","region","local","location","endereco","address","itajai"],
    pt:"Itaja\u00ed, Santa Catarina, Brasil!",
    en:"Itaja\u00ed, Santa Catarina, Brazil!",
    page:"contato", pageLabelPt:"Ver no Mapa", pageLabelEn:"See on Map" },
  { id:"idiomas", keywords:["idioma","lingua","language","ingles","english","fala","speak","portugues","portuguese","bilingue","bilingual","fluente","fluent"],
    pt:"Portugu\u00eas nativo e conhecimento em Ingl\u00eas!",
    en:"Native Portuguese and English knowledge!" },
  { id:"servicos", keywords:["servico","servicos","service","services","oferece","offer","atende","area","atuacao"],
    pt:"Suporte e Infraestrutura (Zabbix/Grafana) e Resolu\u00e7\u00e3o de Incidentes (diagn\u00f3stico \u00e1gil)!",
    en:"Support & Infrastructure and Incident Resolution!" },
  { id:"curriculo", keywords:["curriculo","cv","baixar","download","pdf","documento","document"],
    pt:"Dispon\u00edvel ali em cima, bot\u00e3o 'Baixar Curr\u00edculo'!",
    en:"Available above, 'Download Resume' button!" },
  { id:"programacao", keywords:["programacao","programming","codigo","code","html","css","javascript","python","desenvolvedor","developer","frontend","backend","fullstack","full stack"],
    pt:"HTML, CSS, JavaScript e Python. Foco em front-end. Esse portf\u00f3lio foi feito por ele!",
    en:"HTML, CSS, JavaScript & Python. This portfolio was built by him!" },
  { id:"windowsad", keywords:["windows","active directory","ad","permissao","permission","usuario","user","servidor","server"],
    pt:"Windows AD: permiss\u00f5es, usu\u00e1rios e servidores. Aprendeu na DATAPINE!",
    en:"Windows AD: permissions, users & servers. Learned at DATAPINE!" },
  { id:"moto", keywords:["moto","motorcycle","motocicleta","viagem","travel","interior","road trip","passeio","ride"],
    pt:"Ele adora pegar a moto e conhecer cidades do interior! \u00c9 o hobby favorito dele.",
    en:"He loves riding his motorcycle to explore small towns! It's his favorite hobby." },
  { id:"cafe", keywords:["cafe","coffee","bebe","drink","energetico","energy drink","red bull","monster"],
    pt:"Prefere energ\u00e9tico, mas aceita caf\u00e9 pra resolver um bug!",
    en:"Prefers energy drinks, but takes coffee to fix bugs!" },
  { id:"segredo", keywords:["segredo","secret","escondido","hidden","ninguem sabe","nobody knows","misterio","mystery"],
    pt:"Ele conversa com os servidores... e eles respondem!",
    en:"He talks to the servers... and they talk back!" },
  { id:"ia", keywords:["voce","quem e voce","who are you","e voce","are you","robo","robot","ia","inteligencia artificial","artificial intelligence","chatbot","bot","assistente","assistant"],
    pt:"Sou a Assistente do Ari. Sem f\u00e9rias, sem 13\u00ba... mas adoro fofocar sobre ele!",
    en:"I'm Ari's Assistant. No vacation, no bonuses... but I love gossiping about him!" },
  { id:"elogio", keywords:["legal","cool","bonito","beautiful","incrivel","amazing","show","parabens","top","demais","awesome","massa","nice","lindo","wow"],
    pt:"Vou contar pra ele! Brincadeira... ou n\u00e3o!",
    en:"I'll tell him! Just kidding... or not!" },
  { id:"personalidade", keywords:["personalidade","personality","tipo de pessoa","kind of person","como ele e","what is he like","temperamento","humor","engracado","funny","serio","serious"],
    pt:"S\u00e9rio quando precisa, mas faz piada at\u00e9 em reuni\u00e3o de crise!",
    en:"Serious when needed, but cracks jokes even in crisis meetings!" },
  { id:"objetivo", keywords:["objetivo","goal","sonho","dream","futuro","future","plano","plan","quer ser","wants to be","pretende","intends","ambicao","ambition","meta"],
    pt:"Se aprofundar em tecnologia e alcan\u00e7ar lideran\u00e7a t\u00e9cnica!",
    en:"Go deeper into technology and reach technical leadership!" },
  { id:"signo", keywords:["signo","sign","zodiaco","zodiac","escorpiao","scorpio","horoscopo","horoscope"],
    pt:"31/10 = Escorpi\u00e3o! Intenso, determinado e misterioso.",
    en:"10/31 = Scorpio! Intense, determined, mysterious." }
];
